/*
-- Query: select * from users
LIMIT 0, 1000

-- Date: 2022-12-23 01:15
*/
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (1,'Claire Gute','Fremont','Nebraska',68025);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (2,'Sean O\'Donnell','Provo','Utah',84604);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (3,'Brosina Hoffman','Keller','Texas',76248);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (4,'Andrew Allen','Harlingen','Texas',78550);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (5,'Irene Maddox','Kenner','Louisiana',70065);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (6,'Pete Kriz','Santa Ana','California',92704);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (7,'Alejandro Grove','Pharr','Texas',78577);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (8,'Zuschuss Donatelli','Taylor','Michigan',48180);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (9,'Sandra Flanagan','New Rochelle','New York',10801);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (10,'Emily Burns','Oswego','Illinois',60543);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (11,'Eric Hoffmann','Santa Barbara','California',93101);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (12,'Tracy Blumstein','Lorain','Ohio',44052);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (13,'Patrick O\'Donnell','Bloomington','Illinois',61701);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (14,'Lena Hernandez','Atlanta','Georgia',30318);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (15,'Darren Powers','Moreno Valley','California',92553);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (16,'Ted Butterfield','Redlands','California',92374);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (17,'Kunst Miller','Philadelphia','Pennsylvania',19140);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (18,'Karen Daniels','Park Ridge','Illinois',60068);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (19,'Henry MacAllister','Waco','Texas',76706);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (20,'Joel Eaton','Troy','New York',12180);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (21,'Duane Noonan','Austin','Texas',78745);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (22,'Paul Gonzalez','Lancaster','California',93534);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (23,'Karl Braun','Florence','Kentucky',41042);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (24,'Katherine Ducich','Deltona','Florida',32725);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (25,'Gary Zandusky','Denver','Colorado',80219);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (26,'Lena Cacioppo','Cleveland','Ohio',44105);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (27,'Janet Martin','Mount Vernon','New York',10550);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (28,'Clay Ludtke','Madison','Wisconsin',53711);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (29,'Ryan Crowe','Harrisonburg','Virginia',22801);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (30,'Dave Kipp','Roseville','California',95661);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (31,'Steven Cartwright','Saint Louis','Missouri',63116);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (32,'Philip Fox','Miramar','Florida',33023);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (33,'Troy Staebel','Lake Charles','Louisiana',70601);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (34,'Lena Creighton','Columbus','Ohio',43229);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (35,'Sandra Glassco','Monroe','Louisiana',71203);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (36,'Helen Andreada','Buffalo','New York',14215);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (37,'Dave Brooks','Columbia','South Carolina',29203);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (38,'Nora Paige','Redondo Beach','California',90278);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (39,'Ted Trevino','Dallas','Texas',75220);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (40,'Eric Murdock','Hamilton','Ohio',45011);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (41,'Ruben Dartt','Eagan','Minnesota',55122);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (42,'Max Jones','Commerce City','Colorado',80022);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (43,'Becky Martin','Freeport','New York',11520);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (44,'Chad Sievert','Denver','Colorado',80219);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (45,'Shirley Jackson','Visalia','California',93277);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (46,'Sally Knutson','Pensacola','Florida',32503);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (47,'Cassandra Brandow','Kirkwood','Missouri',63122);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (48,'Maria Bertelson','Hempstead','New York',11550);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (49,'Bruce Stewart','Kenosha','Wisconsin',53142);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (50,'Logan Currie','Sacramento','California',95823);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (51,'Laurel Elliston','Ormond Beach','Florida',32174);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (52,'Joseph Holt','Tempe','Arizona',85281);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (53,'Jonathan Howell','Camarillo','California',93010);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (54,'Joni Blumstein','North Charleston','South Carolina',29406);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (55,'Valerie Dominguez','Rome','New York',13440);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (56,'Ken Lonsdale','Hendersonville','Tennessee',37075);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (57,'Logan Haushalter','Medina','Ohio',44256);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (58,'Kelly Collister','Delray Beach','Florida',33445);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (59,'Delfina Latchford','Boise','Idaho',83704);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (60,'Craig Carreira','Vacaville','California',95687);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (61,'Roy Collins','Little Rock','Arkansas',72209);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (62,'Alan Hwang','North Charleston','South Carolina',29406);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (63,'Jas O\'Carroll','Owensboro','Kentucky',42301);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (64,'Shahid Hopkins','Pasadena','California',91104);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (65,'Patrick O\'Brill','Pensacola','Florida',32503);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (66,'John Lucas','Naperville','Illinois',60540);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (67,'Doug Bickford','Sterling Heights','Michigan',48310);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (68,'Clay Cheatham','North Charleston','South Carolina',29406);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (69,'Tamara Dahlen','Chester','Pennsylvania',19013);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (70,'Jeremy Lonsdale','Lakeville','Minnesota',55044);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (71,'Katrina Willman','Parma','Ohio',44134);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (72,'Julia Dunbar','Kissimmee','Florida',34741);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (73,'Guy Thornton','Hickory','North Carolina',28601);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (74,'Arthur Gainer','Alexandria','Virginia',22304);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (75,'Russell Applegate','Gresham','Oregon',97030);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (76,'Denny Ordway','Frisco','Texas',75034);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (77,'Nathan Gelder','San Antonio','Texas',78207);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (78,'Mike Vittorini','Lake Charles','Louisiana',70601);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (79,'Jack Garza','Bowling Green','Ohio',43402);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (80,'Anna Gayman','Port Saint Lucie','Florida',34952);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (81,'Luke Foster','Coon Rapids','Minnesota',55433);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (82,'Roy Französisch','Franklin','Massachusetts',2038);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (83,'Keith Herrera','Chico','California',95928);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (84,'Caroline Jumper','Cottage Grove','Minnesota',55016);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (85,'Philip Brown','Greenville','North Carolina',27834);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (86,'Natalie Fritzler','Charlotte','North Carolina',28205);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (87,'Mike Kennedy','Las Cruces','New Mexico',88001);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (88,'Troy Blackwell','North Charleston','South Carolina',29406);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (89,'Raymond Buch','Coon Rapids','Minnesota',55433);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (90,'Sanjit Chand','Romeoville','Illinois',60441);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (91,'Jeremy Pistek','Troy','New York',12180);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (92,'Jeremy Ellison','Edmonds','Washington',98026);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (93,'Xylona Preis','Detroit','Michigan',48227);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (94,'Erin Mull','Apopka','Florida',32712);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (95,'Sue Ann Reed','Plantation','Florida',33317);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (96,'Astrea Jones','Mcallen','Texas',78501);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (97,'Sonia Sunley','Pasadena','California',91104);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (98,'Rose O\'Brian','Broomfield','Colorado',80020);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (99,'Maribeth Dona','Belleville','New Jersey',7109);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (100,'Christopher Martinez','Marion','Ohio',43302);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (101,'Lynn Smith','El Paso','Texas',79907);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (102,'Bradley Nguyen','Englewood','Colorado',80112);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (103,'Dean Braden','Buffalo Grove','Illinois',60089);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (104,'Brian Dahlen','Charlotte','North Carolina',28205);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (105,'Mike Gockenbach','Texas City','Texas',77590);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (106,'Jasper Cacioppo','Renton','Washington',98059);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (107,'Rob Lucas','Beaumont','Texas',77705);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (108,'Allen Armold','Hot Springs','Arkansas',71901);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (109,'Emily Phan','Waynesboro','Virginia',22980);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (110,'Darren Koutras','Farmington','New Mexico',87401);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (111,'Bradley Drucker','Taylor','Michigan',48180);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (112,'Liz MacKendrick','Irving','Texas',75061);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (113,'Bill Donatelli','Hialeah','Florida',33012);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (114,'Greg Tran','Reading','Pennsylvania',19601);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (115,'Ashley Jarboe','Chandler','Arizona',85224);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (116,'Olvera Toch','Smyrna','Tennessee',37167);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (117,'Liz Pelletier','North Charleston','South Carolina',29406);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (118,'Cynthia Arntzen','Chattanooga','Tennessee',37421);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (119,'Jeremy Farry','Kenner','Louisiana',70065);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (120,'Frank Preis','Bloomington','Illinois',61701);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (121,'Jennifer Ferguson','Murrieta','California',92563);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (122,'Sarah Foster','Cedar Rapids','Iowa',52402);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (123,'Trudy Glocke','Broomfield','Colorado',80020);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (124,'Carlos Soltero','Frisco','Texas',75034);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (125,'Charles Crestani','San Francisco','California',94109);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (126,'Dianna Vittorini','Commerce City','Colorado',80022);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (127,'Bruce Degenhardt','West Palm Beach','Florida',33407);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (128,'Zuschuss Carroll','East Orange','New Jersey',7017);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (129,'Melanie Seite','Phoenix','Arizona',85023);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (130,'Lena Radford','Nashua','New Hampshire',3060);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (131,'Theone Pippenger','Encinitas','California',92024);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (132,'Chloris Kastensmidt','Kenosha','Wisconsin',53142);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (133,'Alan Shonely','Medford','Oregon',97504);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (134,'Andrew Roberts','Virginia Beach','Virginia',23464);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (135,'Clytie Kelty','Marietta','Georgia',30062);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (136,'Christina Anderson','Austin','Texas',78745);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (137,'Annie Thurman','Hempstead','New York',11550);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (138,'Fred McMath','Atlanta','Georgia',30318);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (139,'Max Engle','Fresno','California',93727);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (140,'John Lee','Plano','Texas',75023);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (141,'Sean Christensen','Lancaster','California',93534);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (142,'Craig Reiter','Kenosha','Wisconsin',53142);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (143,'Resi Pölking','Littleton','Colorado',80122);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (144,'Rob Beeghly','Albuquerque','New Mexico',87105);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (145,'Carol Darley','Chandler','Arizona',85224);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (146,'Doug Jacobs','San Angelo','Texas',76903);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (147,'Michael Chen','Portland','Oregon',97206);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (148,'Ralph Arnett','Tigard','Oregon',97224);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (149,'Naresj Patel','Highland Park','Illinois',60035);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (150,'Alan Barnes','Hagerstown','Maryland',21740);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (151,'Jay Kimmel','Newport News','Virginia',23602);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (152,'David Philippe','Sparks','Nevada',89431);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (153,'Arthur Prichep','Lancaster','California',93534);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (154,'Seth Vernon','Pine Bluff','Arkansas',71603);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (155,'Jay Fein','Tigard','Oregon',97224);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (156,'Emily Grady','Naperville','Illinois',60540);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (157,'Sung Shariari','Margate','Florida',33063);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (158,'Peter Bühler','Troy','New York',12180);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (159,'Roland Fjeld','Marlborough','Massachusetts',1752);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (160,'Debra Catini','Wausau','Wisconsin',54401);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (161,'Lisa Hazard','Mount Vernon','New York',10550);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (162,'Dan Lawera','Pembroke Pines','Florida',33024);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (163,'Bryan Mills','Mission Viejo','California',92691);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (164,'Liz Thompson','Chesapeake','Virginia',23320);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (165,'Joe Kamberova','San Angelo','Texas',76903);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (166,'Erica Smith','Huntington Beach','California',92646);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (167,'Rick Hansen','Margate','Florida',33063);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (168,'Carlos Daly','Beaumont','Texas',77705);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (169,'Gary McGarr','Hialeah','Florida',33012);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (170,'Pauline Johnson','Montgomery','Alabama',36116);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (171,'Toby Ritter','Bullhead City','Arizona',86442);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (172,'Patrick Gardner','Encinitas','California',92024);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (173,'Art Foster','Washington','District of Columbia',20016);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (174,'Guy Armstrong','Suffolk','Virginia',23434);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (175,'Berenike Kampe','Virginia Beach','Virginia',23464);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (176,'Chuck Magee','Cottage Grove','Minnesota',55016);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (177,'Sally Matthias','Lowell','Massachusetts',1852);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (178,'Lauren Leatherbury','Concord','North Carolina',28027);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (179,'Hunter Lopez','Fairfield','Connecticut',6824);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (180,'Maribeth Schnelling','Fort Lauderdale','Florida',33311);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (181,'Sanjit Engle','Midland','Michigan',48640);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (182,'Jessica Myrick','Margate','Florida',33063);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (183,'Ralph Kennedy','Bethlehem','Pennsylvania',18018);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (184,'Katherine Hughes','Florence','Kentucky',41042);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (185,'Greg Hansen','Mesa','Arizona',85204);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (186,'Scott Williamson','Spokane','Washington',99207);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (187,'Joseph Airdo','Goldsboro','North Carolina',27534);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (188,'Daniel Lacy','Waco','Texas',76706);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (189,'Robert Waldorf','Buffalo Grove','Illinois',60089);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (190,'Tracy Zic','Harlingen','Texas',78550);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (191,'Toby Swindell','Arlington','Virginia',22204);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (192,'Rob Dowd','Rochester Hills','Michigan',48307);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (193,'Ryan Akin','Woonsocket','Rhode Island',2895);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (194,'Meg Tillman','Longmont','Colorado',80501);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (195,'Vivek Gonzalez','Lowell','Massachusetts',1852);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (196,'John Stevenson','Longview','Washington',98632);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (197,'Allen Goldenen','Bloomington','Illinois',61701);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (198,'Jennifer Jackson','College Station','Texas',77840);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (199,'Jennifer Halladay','Midland','Michigan',48640);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (200,'Mary O\'Rourke','Pueblo','Colorado',81001);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (201,'Brian DeCherney','Andover','Massachusetts',1810);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (202,'Charles McCrossin','Franklin','Massachusetts',2038);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (203,'Frank Olsen','Waterloo','Iowa',50701);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (204,'Maurice Satty','Kirkwood','Missouri',63122);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (205,'Don Weiss','Rock Hill','South Carolina',29730);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (206,'Neoma Murray','Jonesboro','Arkansas',72401);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (207,'Christine Sundaresam','Jackson','Michigan',49201);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (208,'Nat Carroll','Arlington Heights','Illinois',60004);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (209,'Alex Avila','Evanston','Illinois',60201);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (210,'Larry Tron','Austin','Texas',78745);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (211,'Paul MacIntyre','Chandler','Arizona',85224);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (212,'Larry Hughes','Layton','Utah',84041);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (213,'Kean Thornton','Everett','Massachusetts',2149);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (214,'Greg Matthias','Knoxville','Tennessee',37918);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (215,'Eva Jacobs','Lake Forest','California',92630);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (216,'Nora Preis','Vineland','New Jersey',8360);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (217,'Jocasta Rupert','New Rochelle','New York',10801);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (218,'Chris Cortes','Commerce City','Colorado',80022);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (219,'Phillip Flathmann','Quincy','Illinois',62301);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (220,'Dan Campbell','Hendersonville','Tennessee',37075);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (221,'Bryan Davis','Fargo','North Dakota',58103);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (222,'Gene McClure','Dearborn Heights','Michigan',48127);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (223,'Justin Hirsh','Denver','Colorado',80219);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (224,'Chuck Sachs','Sioux Falls','South Dakota',57103);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (225,'Matt Collins','Chesapeake','Virginia',23320);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (226,'Liz Preis','Plantation','Florida',33317);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (227,'Evan Bailliet','Parma','Ohio',44134);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (228,'Lisa DeCherney','Indianapolis','Indiana',46203);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (229,'Michael Nguyen','Rock Hill','South Carolina',29730);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (230,'Jim Radford','Charlotte','North Carolina',28205);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (231,'Jamie Frazer','Holland','Michigan',49423);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (232,'Chad McGuire','Greenville','North Carolina',27834);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (233,'Beth Paige','Garden City','Kansas',67846);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (234,'Natalie DeCherney','Akron','Ohio',44312);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (235,'Larry Blacks','Oklahoma City','Oklahoma',73120);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (236,'Kean Takahito','North Miami','Florida',33161);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (237,'Adrian Barton','Everett','Massachusetts',2149);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (238,'Helen Abelman','Waco','Texas',76706);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (239,'Shui Tom','Greeley','Colorado',80634);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (240,'Michael Moore','Sandy Springs','Georgia',30328);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (241,'Thais Sissman','Hagerstown','Maryland',21740);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (242,'Mick Brown','Cedar Hill','Texas',75104);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (243,'Cindy Stewart','Albuquerque','New Mexico',87105);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (244,'Maxwell Schwartz','Lubbock','Texas',79424);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (245,'Corey-Lock','Plano','Texas',75023);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (246,'John Dryer','Cottage Grove','Minnesota',55016);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (247,'Andy Reiter','Henderson','Kentucky',42420);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (248,'Arianne Irving','Sandy Springs','Georgia',30328);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (249,'Tom Boeckenhauer','Pearland','Texas',77581);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (250,'Gary Hwang','Rockville','Maryland',20852);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (251,'Carl Ludwig','Marlborough','Massachusetts',1752);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (252,'Ivan Gibson','Orlando','Florida',32839);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (253,'Bobby Odegard','Stockton','California',95207);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (254,'Aimee Bixby','Evanston','Illinois',60201);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (255,'Julia West','Johnson City','Tennessee',37604);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (256,'Sheri Gordon','Bolingbrook','Illinois',60440);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (257,'Charlotte Melton','Roswell','Georgia',30076);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (258,'Anthony Witt','Provo','Utah',84604);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (259,'Mick Crebagga','Abilene','Texas',79605);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (260,'Rick Duston','Alexandria','Virginia',22304);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (261,'Jenna Caffey','Passaic','New Jersey',7055);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (262,'James Galang','Chandler','Arizona',85224);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (263,'Marc Crier','Evanston','Illinois',60201);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (264,'Natalie Webber','Trenton','Michigan',48183);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (265,'Toby Braunhardt','Jackson','Michigan',49201);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (266,'Christina DeMoss','Greenville','North Carolina',27834);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (267,'Thea Hendricks','Deltona','Florida',32725);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (268,'Michelle Moray','Allen','Texas',75002);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (269,'Neola Schneider','Passaic','New Jersey',7055);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (270,'Shaun Weien','Apopka','Florida',32712);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (271,'Eric Barreto','Portland','Oregon',97206);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (272,'Pamela Stobb','Tempe','Arizona',85281);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (273,'Herbert Flentye','Nashua','New Hampshire',3060);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (274,'Henia Zydlo','Lakeville','Minnesota',55044);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (275,'Jamie Kunitz','Lebanon','Tennessee',37087);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (276,'Joni Wasserman','Providence','Rhode Island',2908);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (277,'Raymond Messe','Denver','Colorado',80219);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (278,'Craig Carroll','Little Rock','Arkansas',72209);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (279,'Jill Fjeld','Bowling Green','Ohio',43402);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (280,'Brian Thompson','Palm Coast','Florida',32137);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (281,'Janet Lee','Kent','Washington',98031);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (282,'Giulietta Weimer','Redlands','California',92374);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (283,'Benjamin Patterson','Stockton','California',95207);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (284,'John Castell','Lowell','Massachusetts',1852);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (285,'Adam Shillingsburg','Rockford','Illinois',61107);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (286,'Amy Cox','Royal Oak','Michigan',48073);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (287,'Duane Benoit','Rochester Hills','Michigan',48307);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (288,'Erica Hackney','Deltona','Florida',32725);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (289,'Joe Elijah','Wilmington','Delaware',19805);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (290,'Joy Daniels','Freeport','New York',11520);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (291,'Christy Brittain','Frisco','Texas',75034);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (292,'Joy Smith','Bowling Green','Ohio',43402);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (293,'Luke Weiss','Harlingen','Texas',78550);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (294,'Stuart Calhoun','Frisco','Texas',75034);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (295,'Anne McFarland','Miramar','Florida',33023);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (296,'Carol Triggs','Atlanta','Georgia',30318);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (297,'Kelly Andreada','Commerce City','Colorado',80022);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (298,'Bart Folk','Palm Coast','Florida',32137);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (299,'Magdelene Morse','Fort Worth','Texas',76106);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (300,'Ben Wallace','Decatur','Illinois',62521);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (301,'Scot Wooten','Monroe','Louisiana',71203);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (302,'Brian Stugart','Alexandria','Virginia',22304);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (303,'William Brown','Pensacola','Florida',32503);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (304,'Trudy Brown','Murray','Kentucky',42071);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (305,'Art Ferguson','Paterson','New Jersey',7501);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (306,'Richard Bierner','Grand Prairie','Texas',75051);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (307,'John Huston','Glendale','Arizona',85301);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (308,'Ivan Liston','La Porte','Indiana',46350);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (309,'Rob Haberlin','Ormond Beach','Florida',32174);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (310,'Maris LaWare','Camarillo','California',93010);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (311,'Dennis Kane','Beaumont','Texas',77705);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (312,'Bobby Trafton','Madison','Wisconsin',53711);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (313,'Denny Blanton','Escondido','California',92025);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (314,'Toby Gnade','Austin','Texas',78745);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (315,'Justin MacKendrick','Lorain','Ohio',44052);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (316,'Mitch Webber','Milford','Connecticut',6460);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (317,'Mark Van Huff','Sierra Vista','Arizona',85635);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (318,'Tom Prescott','Utica','New York',13501);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (319,'Jim Karlsson','Fargo','North Dakota',58103);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (320,'Susan Vittorini','Omaha','Nebraska',68104);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (321,'Kelly Williams','Indianapolis','Indiana',46203);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (322,'Christina VanderZanden','Waukesha','Wisconsin',53186);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (323,'Speros Goranitis','Yonkers','New York',10701);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (324,'Tamara Manning','Hattiesburg','Mississippi',39401);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (325,'Annie Zypern','Temecula','California',92592);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (326,'Pierre Wener','Nashville','Tennessee',37211);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (327,'Shahid Collister','Stockton','California',95207);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (328,'Carlos Meador','Salt Lake City','Utah',84106);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (329,'Tim Brockman','Scottsdale','Arizona',85254);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (330,'John Murray','Homestead','Florida',33030);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (331,'Sonia Cooley','Coppell','Texas',75019);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (332,'Ralph Ritter','Warner Robins','Georgia',31088);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (333,'Thomas Thornton','Miramar','Florida',33023);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (334,'Brian Derr','Redmond','Oregon',97756);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (335,'Chris McAfee','Roseville','California',95661);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (336,'Edward Nazzal','Boca Raton','Florida',33433);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (337,'Jason Fortune-','Cottage Grove','Minnesota',55016);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (338,'Sarah Bern','Clovis','New Mexico',88101);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (339,'Hunter Glantz','Fort Worth','Texas',76106);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (340,'Toby Carlisle','Lake Forest','California',92630);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (341,'Stewart Visinsky','New Rochelle','New York',10801);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (342,'Bobby Elias','Brownsville','Texas',78521);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (343,'David Flashing','Atlanta','Georgia',30318);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (344,'Fred Harton','Boynton Beach','Florida',33437);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (345,'MaryBeth Skach','Rancho Cucamonga','California',91730);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (346,'Ritsa Hightower','Chicago','Illinois',60610);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (347,'George Ashbrook','Houston','Texas',77070);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (348,'Michael Oakman','Tallahassee','Florida',32303);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (349,'Denise Leinenbach','Denver','Colorado',80219);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (350,'Michelle Huthwaite','Belleville','New Jersey',7109);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (351,'Darrin Martin','Medina','Ohio',44256);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (352,'Anna Chung','San Mateo','California',94403);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (353,'Christopher Conant','Kirkwood','Missouri',63122);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (354,'Harry Greene','Avondale','Arizona',85323);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (355,'Becky Pak','Inglewood','California',90301);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (356,'Giulietta Baptist','Dubuque','Iowa',52001);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (357,'Joy Bell-','Kent','Washington',98031);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (358,'Richard Eichhorn','Fairfield','Connecticut',6824);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (359,'Erin Creighton','Dallas','Texas',75220);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (360,'Eugene Barchas','Hot Springs','Arkansas',71901);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (361,'Pete Takahito','Marlborough','Massachusetts',1752);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (362,'Jack Lebron','Cedar Rapids','Iowa',52402);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (363,'Cindy Chapman','Arlington Heights','Illinois',60004);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (364,'Sarah Jordon','Marlborough','Massachusetts',1752);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (365,'Bruce Geld','Lakewood','New Jersey',8701);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (366,'Evan Henry','Cedar Hill','Texas',75104);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (367,'Tony Sayre','Saint Charles','Missouri',63301);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (368,'Patrick Ryan','Denver','Colorado',80219);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (369,'Liz Carlisle','Austin','Texas',78745);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (370,'Mark Hamilton','Jacksonville','Florida',32216);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (371,'Russell D\'Ascenzo','Athens','Georgia',30605);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (372,'Sam Craven','Norman','Oklahoma',73071);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (373,'Randy Bradley','Carol Stream','Illinois',60188);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (374,'Roland Murray','Laredo','Texas',78041);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (375,'Vivian Mathis','Costa Mesa','California',92627);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (376,'Ed Jacobs','Royal Oak','Michigan',48073);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (377,'Nathan Cano','Tyler','Texas',75701);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (378,'Lycoris Saunders','Clifton','New Jersey',7011);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (379,'Peter Fuller','Hampton','Virginia',23666);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (380,'Maureen Gnade','Layton','Utah',84041);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (381,'Susan Pistek','Westminster','California',92683);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (382,'Dana Kaydos','Kirkwood','Missouri',63122);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (383,'Khloe Miller','Carlsbad','New Mexico',88220);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (384,'Anna Andreadi','Ontario','California',91761);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (385,'Dorothy Dickinson','Kent','Washington',98031);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (386,'Amy Hunt','Cleveland','Ohio',44105);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (387,'Angele Hood','New Castle','Indiana',47362);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (388,'Roger Demir','Sandy Springs','Georgia',30328);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (389,'Alex Grayson','Milwaukee','Wisconsin',53209);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (390,'Vivek Sundaresam','Jonesboro','Arkansas',72401);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (391,'Tony Molinari','Highland Park','Illinois',60035);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (392,'Nick Radford','New Bedford','Massachusetts',2740);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (393,'Cari Schnelling','Highland Park','Illinois',60035);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (394,'Liz Willingham','Waukesha','Wisconsin',53186);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (395,'Aaron Bergman','Gilbert','Arizona',85234);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (396,'Shahid Shariari','Miami','Florida',33180);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (397,'Jill Matthias','East Orange','New Jersey',7017);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (398,'Muhammed Lee','Coral Springs','Florida',33065);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (399,'Juliana Krohn','Rome','New York',13440);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (400,'Sarah Brown','Woonsocket','Rhode Island',2895);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (401,'Barry Gonzalez','Fort Collins','Colorado',80525);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (402,'Barry Weirich','Fayetteville','Arkansas',72701);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (403,'Doug O\'Connell','Logan','Utah',84321);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (404,'Trudy Schmidt','Watertown','New York',13601);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (405,'Ionia McGrath','Plainfield','New Jersey',7060);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (406,'Anemone Ratner','Mission Viejo','California',92691);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (407,'Sung Chung','Abilene','Texas',79605);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (408,'Ricardo Emerson','Jackson','Michigan',49201);
INSERT INTO `` (`customer_id`,`name`,`city`,`state`,`postal`) VALUES (409,'Susan MacKendrick','Rogers','Arkansas',72756);
